/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PPetSlugIndexRouteImport } from './routes/p/$petSlug/index'
import { Route as AppPetsIndexRouteImport } from './routes/app/pets/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as PPetSlugArchiveRouteImport } from './routes/p/$petSlug/archive'
import { Route as PPetSlugAboutRouteImport } from './routes/p/$petSlug/about'
import { Route as AppPetsNewRouteImport } from './routes/app/pets/new'
import { Route as AppGenerationsJobIdRouteImport } from './routes/app/generations.$jobId'
import { Route as AppAdminJobsRouteImport } from './routes/app/admin/jobs'
import { Route as AppAdminCostsRouteImport } from './routes/app/admin/costs'
import { Route as PPetSlugPostsPostSlugRouteImport } from './routes/p/$petSlug/posts/$postSlug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPetSlugIndexRoute = PPetSlugIndexRouteImport.update({
  id: '/p/$petSlug/',
  path: '/p/$petSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPetsIndexRoute = AppPetsIndexRouteImport.update({
  id: '/app/pets/',
  path: '/app/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/app/admin/',
  path: '/app/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPetSlugArchiveRoute = PPetSlugArchiveRouteImport.update({
  id: '/p/$petSlug/archive',
  path: '/p/$petSlug/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const PPetSlugAboutRoute = PPetSlugAboutRouteImport.update({
  id: '/p/$petSlug/about',
  path: '/p/$petSlug/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPetsNewRoute = AppPetsNewRouteImport.update({
  id: '/app/pets/new',
  path: '/app/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGenerationsJobIdRoute = AppGenerationsJobIdRouteImport.update({
  id: '/app/generations/$jobId',
  path: '/app/generations/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminJobsRoute = AppAdminJobsRouteImport.update({
  id: '/app/admin/jobs',
  path: '/app/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminCostsRoute = AppAdminCostsRouteImport.update({
  id: '/app/admin/costs',
  path: '/app/admin/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const PPetSlugPostsPostSlugRoute = PPetSlugPostsPostSlugRouteImport.update({
  id: '/p/$petSlug/posts/$postSlug',
  path: '/p/$petSlug/posts/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/costs': typeof AppAdminCostsRoute
  '/app/admin/jobs': typeof AppAdminJobsRoute
  '/app/generations/$jobId': typeof AppGenerationsJobIdRoute
  '/app/pets/new': typeof AppPetsNewRoute
  '/p/$petSlug/about': typeof PPetSlugAboutRoute
  '/p/$petSlug/archive': typeof PPetSlugArchiveRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/pets/': typeof AppPetsIndexRoute
  '/p/$petSlug/': typeof PPetSlugIndexRoute
  '/p/$petSlug/posts/$postSlug': typeof PPetSlugPostsPostSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/admin/costs': typeof AppAdminCostsRoute
  '/app/admin/jobs': typeof AppAdminJobsRoute
  '/app/generations/$jobId': typeof AppGenerationsJobIdRoute
  '/app/pets/new': typeof AppPetsNewRoute
  '/p/$petSlug/about': typeof PPetSlugAboutRoute
  '/p/$petSlug/archive': typeof PPetSlugArchiveRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/pets': typeof AppPetsIndexRoute
  '/p/$petSlug': typeof PPetSlugIndexRoute
  '/p/$petSlug/posts/$postSlug': typeof PPetSlugPostsPostSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/costs': typeof AppAdminCostsRoute
  '/app/admin/jobs': typeof AppAdminJobsRoute
  '/app/generations/$jobId': typeof AppGenerationsJobIdRoute
  '/app/pets/new': typeof AppPetsNewRoute
  '/p/$petSlug/about': typeof PPetSlugAboutRoute
  '/p/$petSlug/archive': typeof PPetSlugArchiveRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/pets/': typeof AppPetsIndexRoute
  '/p/$petSlug/': typeof PPetSlugIndexRoute
  '/p/$petSlug/posts/$postSlug': typeof PPetSlugPostsPostSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/app/'
    | '/app/admin/costs'
    | '/app/admin/jobs'
    | '/app/generations/$jobId'
    | '/app/pets/new'
    | '/p/$petSlug/about'
    | '/p/$petSlug/archive'
    | '/app/admin/'
    | '/app/pets/'
    | '/p/$petSlug/'
    | '/p/$petSlug/posts/$postSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/app'
    | '/app/admin/costs'
    | '/app/admin/jobs'
    | '/app/generations/$jobId'
    | '/app/pets/new'
    | '/p/$petSlug/about'
    | '/p/$petSlug/archive'
    | '/app/admin'
    | '/app/pets'
    | '/p/$petSlug'
    | '/p/$petSlug/posts/$postSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/app/'
    | '/app/admin/costs'
    | '/app/admin/jobs'
    | '/app/generations/$jobId'
    | '/app/pets/new'
    | '/p/$petSlug/about'
    | '/p/$petSlug/archive'
    | '/app/admin/'
    | '/app/pets/'
    | '/p/$petSlug/'
    | '/p/$petSlug/posts/$postSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminCostsRoute: typeof AppAdminCostsRoute
  AppAdminJobsRoute: typeof AppAdminJobsRoute
  AppGenerationsJobIdRoute: typeof AppGenerationsJobIdRoute
  AppPetsNewRoute: typeof AppPetsNewRoute
  PPetSlugAboutRoute: typeof PPetSlugAboutRoute
  PPetSlugArchiveRoute: typeof PPetSlugArchiveRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppPetsIndexRoute: typeof AppPetsIndexRoute
  PPetSlugIndexRoute: typeof PPetSlugIndexRoute
  PPetSlugPostsPostSlugRoute: typeof PPetSlugPostsPostSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$petSlug/': {
      id: '/p/$petSlug/'
      path: '/p/$petSlug'
      fullPath: '/p/$petSlug/'
      preLoaderRoute: typeof PPetSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pets/': {
      id: '/app/pets/'
      path: '/app/pets'
      fullPath: '/app/pets/'
      preLoaderRoute: typeof AppPetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/app/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$petSlug/archive': {
      id: '/p/$petSlug/archive'
      path: '/p/$petSlug/archive'
      fullPath: '/p/$petSlug/archive'
      preLoaderRoute: typeof PPetSlugArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$petSlug/about': {
      id: '/p/$petSlug/about'
      path: '/p/$petSlug/about'
      fullPath: '/p/$petSlug/about'
      preLoaderRoute: typeof PPetSlugAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pets/new': {
      id: '/app/pets/new'
      path: '/app/pets/new'
      fullPath: '/app/pets/new'
      preLoaderRoute: typeof AppPetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/generations/$jobId': {
      id: '/app/generations/$jobId'
      path: '/app/generations/$jobId'
      fullPath: '/app/generations/$jobId'
      preLoaderRoute: typeof AppGenerationsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/jobs': {
      id: '/app/admin/jobs'
      path: '/app/admin/jobs'
      fullPath: '/app/admin/jobs'
      preLoaderRoute: typeof AppAdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/costs': {
      id: '/app/admin/costs'
      path: '/app/admin/costs'
      fullPath: '/app/admin/costs'
      preLoaderRoute: typeof AppAdminCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$petSlug/posts/$postSlug': {
      id: '/p/$petSlug/posts/$postSlug'
      path: '/p/$petSlug/posts/$postSlug'
      fullPath: '/p/$petSlug/posts/$postSlug'
      preLoaderRoute: typeof PPetSlugPostsPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminCostsRoute: AppAdminCostsRoute,
  AppAdminJobsRoute: AppAdminJobsRoute,
  AppGenerationsJobIdRoute: AppGenerationsJobIdRoute,
  AppPetsNewRoute: AppPetsNewRoute,
  PPetSlugAboutRoute: PPetSlugAboutRoute,
  PPetSlugArchiveRoute: PPetSlugArchiveRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppPetsIndexRoute: AppPetsIndexRoute,
  PPetSlugIndexRoute: PPetSlugIndexRoute,
  PPetSlugPostsPostSlugRoute: PPetSlugPostsPostSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
