/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCastRouteImport } from './routes/app/cast'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as PPetSlugIndexRouteImport } from './routes/p/$petSlug/index'
import { Route as AppPetsIndexRouteImport } from './routes/app/pets/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as PPetSlugArchiveRouteImport } from './routes/p/$petSlug/archive'
import { Route as PPetSlugAboutRouteImport } from './routes/p/$petSlug/about'
import { Route as AppPetsNewRouteImport } from './routes/app/pets/new'
import { Route as AppPetsPetIdRouteImport } from './routes/app/pets/$petId'
import { Route as AppGenerationsJobIdRouteImport } from './routes/app/generations.$jobId'
import { Route as AppCastNewRouteImport } from './routes/app/cast.new'
import { Route as AppCastCastMemberIdRouteImport } from './routes/app/cast.$castMemberId'
import { Route as AppAdminTraitsRouteImport } from './routes/app/admin/traits'
import { Route as AppAdminNarratorsRouteImport } from './routes/app/admin/narrators'
import { Route as AppAdminModerationRouteImport } from './routes/app/admin/moderation'
import { Route as AppAdminJobsRouteImport } from './routes/app/admin/jobs'
import { Route as AppAdminCostsRouteImport } from './routes/app/admin/costs'
import { Route as AppAdminArtStylesRouteImport } from './routes/app/admin/art-styles'
import { Route as AppPetsPetIdIndexRouteImport } from './routes/app/pets/$petId/index'
import { Route as PPetSlugPostsPostSlugRouteImport } from './routes/p/$petSlug/posts/$postSlug'
import { Route as AppPetsPetIdMemoriesRouteRouteImport } from './routes/app/pets/$petId/memories/route'
import { Route as AppPetsPetIdMemoriesIndexRouteImport } from './routes/app/pets/$petId/memories/index'
import { Route as AppPetsPetIdMemoriesNewRouteImport } from './routes/app/pets/$petId/memories/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCastRoute = AppCastRouteImport.update({
  id: '/cast',
  path: '/cast',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const PPetSlugIndexRoute = PPetSlugIndexRouteImport.update({
  id: '/p/$petSlug/',
  path: '/p/$petSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPetsIndexRoute = AppPetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const PPetSlugArchiveRoute = PPetSlugArchiveRouteImport.update({
  id: '/p/$petSlug/archive',
  path: '/p/$petSlug/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const PPetSlugAboutRoute = PPetSlugAboutRouteImport.update({
  id: '/p/$petSlug/about',
  path: '/p/$petSlug/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPetsNewRoute = AppPetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPetsPetIdRoute = AppPetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGenerationsJobIdRoute = AppGenerationsJobIdRouteImport.update({
  id: '/generations/$jobId',
  path: '/generations/$jobId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCastNewRoute = AppCastNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCastRoute,
} as any)
const AppCastCastMemberIdRoute = AppCastCastMemberIdRouteImport.update({
  id: '/$castMemberId',
  path: '/$castMemberId',
  getParentRoute: () => AppCastRoute,
} as any)
const AppAdminTraitsRoute = AppAdminTraitsRouteImport.update({
  id: '/traits',
  path: '/traits',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminNarratorsRoute = AppAdminNarratorsRouteImport.update({
  id: '/narrators',
  path: '/narrators',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminModerationRoute = AppAdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminJobsRoute = AppAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminCostsRoute = AppAdminCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminArtStylesRoute = AppAdminArtStylesRouteImport.update({
  id: '/art-styles',
  path: '/art-styles',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppPetsPetIdIndexRoute = AppPetsPetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPetsPetIdRoute,
} as any)
const PPetSlugPostsPostSlugRoute = PPetSlugPostsPostSlugRouteImport.update({
  id: '/p/$petSlug/posts/$postSlug',
  path: '/p/$petSlug/posts/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPetsPetIdMemoriesRouteRoute =
  AppPetsPetIdMemoriesRouteRouteImport.update({
    id: '/memories',
    path: '/memories',
    getParentRoute: () => AppPetsPetIdRoute,
  } as any)
const AppPetsPetIdMemoriesIndexRoute =
  AppPetsPetIdMemoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPetsPetIdMemoriesRouteRoute,
  } as any)
const AppPetsPetIdMemoriesNewRoute = AppPetsPetIdMemoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPetsPetIdMemoriesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/cast': typeof AppCastRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/art-styles': typeof AppAdminArtStylesRoute
  '/app/admin/costs': typeof AppAdminCostsRoute
  '/app/admin/jobs': typeof AppAdminJobsRoute
  '/app/admin/moderation': typeof AppAdminModerationRoute
  '/app/admin/narrators': typeof AppAdminNarratorsRoute
  '/app/admin/traits': typeof AppAdminTraitsRoute
  '/app/cast/$castMemberId': typeof AppCastCastMemberIdRoute
  '/app/cast/new': typeof AppCastNewRoute
  '/app/generations/$jobId': typeof AppGenerationsJobIdRoute
  '/app/pets/$petId': typeof AppPetsPetIdRouteWithChildren
  '/app/pets/new': typeof AppPetsNewRoute
  '/p/$petSlug/about': typeof PPetSlugAboutRoute
  '/p/$petSlug/archive': typeof PPetSlugArchiveRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/pets/': typeof AppPetsIndexRoute
  '/p/$petSlug/': typeof PPetSlugIndexRoute
  '/app/pets/$petId/memories': typeof AppPetsPetIdMemoriesRouteRouteWithChildren
  '/p/$petSlug/posts/$postSlug': typeof PPetSlugPostsPostSlugRoute
  '/app/pets/$petId/': typeof AppPetsPetIdIndexRoute
  '/app/pets/$petId/memories/new': typeof AppPetsPetIdMemoriesNewRoute
  '/app/pets/$petId/memories/': typeof AppPetsPetIdMemoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app/account': typeof AppAccountRoute
  '/app/cast': typeof AppCastRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/admin/art-styles': typeof AppAdminArtStylesRoute
  '/app/admin/costs': typeof AppAdminCostsRoute
  '/app/admin/jobs': typeof AppAdminJobsRoute
  '/app/admin/moderation': typeof AppAdminModerationRoute
  '/app/admin/narrators': typeof AppAdminNarratorsRoute
  '/app/admin/traits': typeof AppAdminTraitsRoute
  '/app/cast/$castMemberId': typeof AppCastCastMemberIdRoute
  '/app/cast/new': typeof AppCastNewRoute
  '/app/generations/$jobId': typeof AppGenerationsJobIdRoute
  '/app/pets/new': typeof AppPetsNewRoute
  '/p/$petSlug/about': typeof PPetSlugAboutRoute
  '/p/$petSlug/archive': typeof PPetSlugArchiveRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/pets': typeof AppPetsIndexRoute
  '/p/$petSlug': typeof PPetSlugIndexRoute
  '/p/$petSlug/posts/$postSlug': typeof PPetSlugPostsPostSlugRoute
  '/app/pets/$petId': typeof AppPetsPetIdIndexRoute
  '/app/pets/$petId/memories/new': typeof AppPetsPetIdMemoriesNewRoute
  '/app/pets/$petId/memories': typeof AppPetsPetIdMemoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/cast': typeof AppCastRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/art-styles': typeof AppAdminArtStylesRoute
  '/app/admin/costs': typeof AppAdminCostsRoute
  '/app/admin/jobs': typeof AppAdminJobsRoute
  '/app/admin/moderation': typeof AppAdminModerationRoute
  '/app/admin/narrators': typeof AppAdminNarratorsRoute
  '/app/admin/traits': typeof AppAdminTraitsRoute
  '/app/cast/$castMemberId': typeof AppCastCastMemberIdRoute
  '/app/cast/new': typeof AppCastNewRoute
  '/app/generations/$jobId': typeof AppGenerationsJobIdRoute
  '/app/pets/$petId': typeof AppPetsPetIdRouteWithChildren
  '/app/pets/new': typeof AppPetsNewRoute
  '/p/$petSlug/about': typeof PPetSlugAboutRoute
  '/p/$petSlug/archive': typeof PPetSlugArchiveRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/pets/': typeof AppPetsIndexRoute
  '/p/$petSlug/': typeof PPetSlugIndexRoute
  '/app/pets/$petId/memories': typeof AppPetsPetIdMemoriesRouteRouteWithChildren
  '/p/$petSlug/posts/$postSlug': typeof PPetSlugPostsPostSlugRoute
  '/app/pets/$petId/': typeof AppPetsPetIdIndexRoute
  '/app/pets/$petId/memories/new': typeof AppPetsPetIdMemoriesNewRoute
  '/app/pets/$petId/memories/': typeof AppPetsPetIdMemoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/login'
    | '/app/admin'
    | '/app/account'
    | '/app/cast'
    | '/app/'
    | '/app/admin/art-styles'
    | '/app/admin/costs'
    | '/app/admin/jobs'
    | '/app/admin/moderation'
    | '/app/admin/narrators'
    | '/app/admin/traits'
    | '/app/cast/$castMemberId'
    | '/app/cast/new'
    | '/app/generations/$jobId'
    | '/app/pets/$petId'
    | '/app/pets/new'
    | '/p/$petSlug/about'
    | '/p/$petSlug/archive'
    | '/app/admin/'
    | '/app/pets/'
    | '/p/$petSlug/'
    | '/app/pets/$petId/memories'
    | '/p/$petSlug/posts/$postSlug'
    | '/app/pets/$petId/'
    | '/app/pets/$petId/memories/new'
    | '/app/pets/$petId/memories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/app/account'
    | '/app/cast'
    | '/app'
    | '/app/admin/art-styles'
    | '/app/admin/costs'
    | '/app/admin/jobs'
    | '/app/admin/moderation'
    | '/app/admin/narrators'
    | '/app/admin/traits'
    | '/app/cast/$castMemberId'
    | '/app/cast/new'
    | '/app/generations/$jobId'
    | '/app/pets/new'
    | '/p/$petSlug/about'
    | '/p/$petSlug/archive'
    | '/app/admin'
    | '/app/pets'
    | '/p/$petSlug'
    | '/p/$petSlug/posts/$postSlug'
    | '/app/pets/$petId'
    | '/app/pets/$petId/memories/new'
    | '/app/pets/$petId/memories'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/about'
    | '/login'
    | '/app/admin'
    | '/app/account'
    | '/app/cast'
    | '/app/'
    | '/app/admin/art-styles'
    | '/app/admin/costs'
    | '/app/admin/jobs'
    | '/app/admin/moderation'
    | '/app/admin/narrators'
    | '/app/admin/traits'
    | '/app/cast/$castMemberId'
    | '/app/cast/new'
    | '/app/generations/$jobId'
    | '/app/pets/$petId'
    | '/app/pets/new'
    | '/p/$petSlug/about'
    | '/p/$petSlug/archive'
    | '/app/admin/'
    | '/app/pets/'
    | '/p/$petSlug/'
    | '/app/pets/$petId/memories'
    | '/p/$petSlug/posts/$postSlug'
    | '/app/pets/$petId/'
    | '/app/pets/$petId/memories/new'
    | '/app/pets/$petId/memories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PPetSlugAboutRoute: typeof PPetSlugAboutRoute
  PPetSlugArchiveRoute: typeof PPetSlugArchiveRoute
  PPetSlugIndexRoute: typeof PPetSlugIndexRoute
  PPetSlugPostsPostSlugRoute: typeof PPetSlugPostsPostSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cast': {
      id: '/app/cast'
      path: '/cast'
      fullPath: '/app/cast'
      preLoaderRoute: typeof AppCastRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/p/$petSlug/': {
      id: '/p/$petSlug/'
      path: '/p/$petSlug'
      fullPath: '/p/$petSlug/'
      preLoaderRoute: typeof PPetSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pets/': {
      id: '/app/pets/'
      path: '/pets'
      fullPath: '/app/pets/'
      preLoaderRoute: typeof AppPetsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/p/$petSlug/archive': {
      id: '/p/$petSlug/archive'
      path: '/p/$petSlug/archive'
      fullPath: '/p/$petSlug/archive'
      preLoaderRoute: typeof PPetSlugArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$petSlug/about': {
      id: '/p/$petSlug/about'
      path: '/p/$petSlug/about'
      fullPath: '/p/$petSlug/about'
      preLoaderRoute: typeof PPetSlugAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pets/new': {
      id: '/app/pets/new'
      path: '/pets/new'
      fullPath: '/app/pets/new'
      preLoaderRoute: typeof AppPetsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pets/$petId': {
      id: '/app/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/app/pets/$petId'
      preLoaderRoute: typeof AppPetsPetIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/generations/$jobId': {
      id: '/app/generations/$jobId'
      path: '/generations/$jobId'
      fullPath: '/app/generations/$jobId'
      preLoaderRoute: typeof AppGenerationsJobIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cast/new': {
      id: '/app/cast/new'
      path: '/new'
      fullPath: '/app/cast/new'
      preLoaderRoute: typeof AppCastNewRouteImport
      parentRoute: typeof AppCastRoute
    }
    '/app/cast/$castMemberId': {
      id: '/app/cast/$castMemberId'
      path: '/$castMemberId'
      fullPath: '/app/cast/$castMemberId'
      preLoaderRoute: typeof AppCastCastMemberIdRouteImport
      parentRoute: typeof AppCastRoute
    }
    '/app/admin/traits': {
      id: '/app/admin/traits'
      path: '/traits'
      fullPath: '/app/admin/traits'
      preLoaderRoute: typeof AppAdminTraitsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/narrators': {
      id: '/app/admin/narrators'
      path: '/narrators'
      fullPath: '/app/admin/narrators'
      preLoaderRoute: typeof AppAdminNarratorsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/moderation': {
      id: '/app/admin/moderation'
      path: '/moderation'
      fullPath: '/app/admin/moderation'
      preLoaderRoute: typeof AppAdminModerationRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/jobs': {
      id: '/app/admin/jobs'
      path: '/jobs'
      fullPath: '/app/admin/jobs'
      preLoaderRoute: typeof AppAdminJobsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/costs': {
      id: '/app/admin/costs'
      path: '/costs'
      fullPath: '/app/admin/costs'
      preLoaderRoute: typeof AppAdminCostsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/art-styles': {
      id: '/app/admin/art-styles'
      path: '/art-styles'
      fullPath: '/app/admin/art-styles'
      preLoaderRoute: typeof AppAdminArtStylesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/pets/$petId/': {
      id: '/app/pets/$petId/'
      path: '/'
      fullPath: '/app/pets/$petId/'
      preLoaderRoute: typeof AppPetsPetIdIndexRouteImport
      parentRoute: typeof AppPetsPetIdRoute
    }
    '/p/$petSlug/posts/$postSlug': {
      id: '/p/$petSlug/posts/$postSlug'
      path: '/p/$petSlug/posts/$postSlug'
      fullPath: '/p/$petSlug/posts/$postSlug'
      preLoaderRoute: typeof PPetSlugPostsPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pets/$petId/memories': {
      id: '/app/pets/$petId/memories'
      path: '/memories'
      fullPath: '/app/pets/$petId/memories'
      preLoaderRoute: typeof AppPetsPetIdMemoriesRouteRouteImport
      parentRoute: typeof AppPetsPetIdRoute
    }
    '/app/pets/$petId/memories/': {
      id: '/app/pets/$petId/memories/'
      path: '/'
      fullPath: '/app/pets/$petId/memories/'
      preLoaderRoute: typeof AppPetsPetIdMemoriesIndexRouteImport
      parentRoute: typeof AppPetsPetIdMemoriesRouteRoute
    }
    '/app/pets/$petId/memories/new': {
      id: '/app/pets/$petId/memories/new'
      path: '/new'
      fullPath: '/app/pets/$petId/memories/new'
      preLoaderRoute: typeof AppPetsPetIdMemoriesNewRouteImport
      parentRoute: typeof AppPetsPetIdMemoriesRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminArtStylesRoute: typeof AppAdminArtStylesRoute
  AppAdminCostsRoute: typeof AppAdminCostsRoute
  AppAdminJobsRoute: typeof AppAdminJobsRoute
  AppAdminModerationRoute: typeof AppAdminModerationRoute
  AppAdminNarratorsRoute: typeof AppAdminNarratorsRoute
  AppAdminTraitsRoute: typeof AppAdminTraitsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminArtStylesRoute: AppAdminArtStylesRoute,
  AppAdminCostsRoute: AppAdminCostsRoute,
  AppAdminJobsRoute: AppAdminJobsRoute,
  AppAdminModerationRoute: AppAdminModerationRoute,
  AppAdminNarratorsRoute: AppAdminNarratorsRoute,
  AppAdminTraitsRoute: AppAdminTraitsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppCastRouteChildren {
  AppCastCastMemberIdRoute: typeof AppCastCastMemberIdRoute
  AppCastNewRoute: typeof AppCastNewRoute
}

const AppCastRouteChildren: AppCastRouteChildren = {
  AppCastCastMemberIdRoute: AppCastCastMemberIdRoute,
  AppCastNewRoute: AppCastNewRoute,
}

const AppCastRouteWithChildren =
  AppCastRoute._addFileChildren(AppCastRouteChildren)

interface AppPetsPetIdMemoriesRouteRouteChildren {
  AppPetsPetIdMemoriesNewRoute: typeof AppPetsPetIdMemoriesNewRoute
  AppPetsPetIdMemoriesIndexRoute: typeof AppPetsPetIdMemoriesIndexRoute
}

const AppPetsPetIdMemoriesRouteRouteChildren: AppPetsPetIdMemoriesRouteRouteChildren =
  {
    AppPetsPetIdMemoriesNewRoute: AppPetsPetIdMemoriesNewRoute,
    AppPetsPetIdMemoriesIndexRoute: AppPetsPetIdMemoriesIndexRoute,
  }

const AppPetsPetIdMemoriesRouteRouteWithChildren =
  AppPetsPetIdMemoriesRouteRoute._addFileChildren(
    AppPetsPetIdMemoriesRouteRouteChildren,
  )

interface AppPetsPetIdRouteChildren {
  AppPetsPetIdMemoriesRouteRoute: typeof AppPetsPetIdMemoriesRouteRouteWithChildren
  AppPetsPetIdIndexRoute: typeof AppPetsPetIdIndexRoute
}

const AppPetsPetIdRouteChildren: AppPetsPetIdRouteChildren = {
  AppPetsPetIdMemoriesRouteRoute: AppPetsPetIdMemoriesRouteRouteWithChildren,
  AppPetsPetIdIndexRoute: AppPetsPetIdIndexRoute,
}

const AppPetsPetIdRouteWithChildren = AppPetsPetIdRoute._addFileChildren(
  AppPetsPetIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppAccountRoute: typeof AppAccountRoute
  AppCastRoute: typeof AppCastRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppGenerationsJobIdRoute: typeof AppGenerationsJobIdRoute
  AppPetsPetIdRoute: typeof AppPetsPetIdRouteWithChildren
  AppPetsNewRoute: typeof AppPetsNewRoute
  AppPetsIndexRoute: typeof AppPetsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppAccountRoute: AppAccountRoute,
  AppCastRoute: AppCastRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppGenerationsJobIdRoute: AppGenerationsJobIdRoute,
  AppPetsPetIdRoute: AppPetsPetIdRouteWithChildren,
  AppPetsNewRoute: AppPetsNewRoute,
  AppPetsIndexRoute: AppPetsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PPetSlugAboutRoute: PPetSlugAboutRoute,
  PPetSlugArchiveRoute: PPetSlugArchiveRoute,
  PPetSlugIndexRoute: PPetSlugIndexRoute,
  PPetSlugPostsPostSlugRoute: PPetSlugPostsPostSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
