/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as PPetSlugIndexRouteImport } from './routes/p/$petSlug/index'
import { Route as AppPetsIndexRouteImport } from './routes/app/pets/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as PPetSlugArchiveRouteImport } from './routes/p/$petSlug/archive'
import { Route as PPetSlugAboutRouteImport } from './routes/p/$petSlug/about'
import { Route as AppPetsNewRouteImport } from './routes/app/pets/new'
import { Route as AppPetsPetIdRouteImport } from './routes/app/pets/$petId'
import { Route as AppGenerationsJobIdRouteImport } from './routes/app/generations.$jobId'
import { Route as AppAdminJobsRouteImport } from './routes/app/admin/jobs'
import { Route as AppAdminCostsRouteImport } from './routes/app/admin/costs'
import { Route as PPetSlugPostsPostSlugRouteImport } from './routes/p/$petSlug/posts/$postSlug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const PPetSlugIndexRoute = PPetSlugIndexRouteImport.update({
  id: '/p/$petSlug/',
  path: '/p/$petSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPetsIndexRoute = AppPetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PPetSlugArchiveRoute = PPetSlugArchiveRouteImport.update({
  id: '/p/$petSlug/archive',
  path: '/p/$petSlug/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const PPetSlugAboutRoute = PPetSlugAboutRouteImport.update({
  id: '/p/$petSlug/about',
  path: '/p/$petSlug/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPetsNewRoute = AppPetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPetsPetIdRoute = AppPetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGenerationsJobIdRoute = AppGenerationsJobIdRouteImport.update({
  id: '/generations/$jobId',
  path: '/generations/$jobId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminJobsRoute = AppAdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminCostsRoute = AppAdminCostsRouteImport.update({
  id: '/admin/costs',
  path: '/admin/costs',
  getParentRoute: () => AppRouteRoute,
} as any)
const PPetSlugPostsPostSlugRoute = PPetSlugPostsPostSlugRouteImport.update({
  id: '/p/$petSlug/posts/$postSlug',
  path: '/p/$petSlug/posts/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app/account': typeof AppAccountRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/costs': typeof AppAdminCostsRoute
  '/app/admin/jobs': typeof AppAdminJobsRoute
  '/app/generations/$jobId': typeof AppGenerationsJobIdRoute
  '/app/pets/$petId': typeof AppPetsPetIdRoute
  '/app/pets/new': typeof AppPetsNewRoute
  '/p/$petSlug/about': typeof PPetSlugAboutRoute
  '/p/$petSlug/archive': typeof PPetSlugArchiveRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/pets/': typeof AppPetsIndexRoute
  '/p/$petSlug/': typeof PPetSlugIndexRoute
  '/p/$petSlug/posts/$postSlug': typeof PPetSlugPostsPostSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app/account': typeof AppAccountRoute
  '/app': typeof AppIndexRoute
  '/app/admin/costs': typeof AppAdminCostsRoute
  '/app/admin/jobs': typeof AppAdminJobsRoute
  '/app/generations/$jobId': typeof AppGenerationsJobIdRoute
  '/app/pets/$petId': typeof AppPetsPetIdRoute
  '/app/pets/new': typeof AppPetsNewRoute
  '/p/$petSlug/about': typeof PPetSlugAboutRoute
  '/p/$petSlug/archive': typeof PPetSlugArchiveRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/pets': typeof AppPetsIndexRoute
  '/p/$petSlug': typeof PPetSlugIndexRoute
  '/p/$petSlug/posts/$postSlug': typeof PPetSlugPostsPostSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/app/account': typeof AppAccountRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/costs': typeof AppAdminCostsRoute
  '/app/admin/jobs': typeof AppAdminJobsRoute
  '/app/generations/$jobId': typeof AppGenerationsJobIdRoute
  '/app/pets/$petId': typeof AppPetsPetIdRoute
  '/app/pets/new': typeof AppPetsNewRoute
  '/p/$petSlug/about': typeof PPetSlugAboutRoute
  '/p/$petSlug/archive': typeof PPetSlugArchiveRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/pets/': typeof AppPetsIndexRoute
  '/p/$petSlug/': typeof PPetSlugIndexRoute
  '/p/$petSlug/posts/$postSlug': typeof PPetSlugPostsPostSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/login'
    | '/app/account'
    | '/app/'
    | '/app/admin/costs'
    | '/app/admin/jobs'
    | '/app/generations/$jobId'
    | '/app/pets/$petId'
    | '/app/pets/new'
    | '/p/$petSlug/about'
    | '/p/$petSlug/archive'
    | '/app/admin/'
    | '/app/pets/'
    | '/p/$petSlug/'
    | '/p/$petSlug/posts/$postSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/app/account'
    | '/app'
    | '/app/admin/costs'
    | '/app/admin/jobs'
    | '/app/generations/$jobId'
    | '/app/pets/$petId'
    | '/app/pets/new'
    | '/p/$petSlug/about'
    | '/p/$petSlug/archive'
    | '/app/admin'
    | '/app/pets'
    | '/p/$petSlug'
    | '/p/$petSlug/posts/$postSlug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/about'
    | '/login'
    | '/app/account'
    | '/app/'
    | '/app/admin/costs'
    | '/app/admin/jobs'
    | '/app/generations/$jobId'
    | '/app/pets/$petId'
    | '/app/pets/new'
    | '/p/$petSlug/about'
    | '/p/$petSlug/archive'
    | '/app/admin/'
    | '/app/pets/'
    | '/p/$petSlug/'
    | '/p/$petSlug/posts/$postSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PPetSlugAboutRoute: typeof PPetSlugAboutRoute
  PPetSlugArchiveRoute: typeof PPetSlugArchiveRoute
  PPetSlugIndexRoute: typeof PPetSlugIndexRoute
  PPetSlugPostsPostSlugRoute: typeof PPetSlugPostsPostSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/p/$petSlug/': {
      id: '/p/$petSlug/'
      path: '/p/$petSlug'
      fullPath: '/p/$petSlug/'
      preLoaderRoute: typeof PPetSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pets/': {
      id: '/app/pets/'
      path: '/pets'
      fullPath: '/app/pets/'
      preLoaderRoute: typeof AppPetsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/p/$petSlug/archive': {
      id: '/p/$petSlug/archive'
      path: '/p/$petSlug/archive'
      fullPath: '/p/$petSlug/archive'
      preLoaderRoute: typeof PPetSlugArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$petSlug/about': {
      id: '/p/$petSlug/about'
      path: '/p/$petSlug/about'
      fullPath: '/p/$petSlug/about'
      preLoaderRoute: typeof PPetSlugAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pets/new': {
      id: '/app/pets/new'
      path: '/pets/new'
      fullPath: '/app/pets/new'
      preLoaderRoute: typeof AppPetsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pets/$petId': {
      id: '/app/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/app/pets/$petId'
      preLoaderRoute: typeof AppPetsPetIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/generations/$jobId': {
      id: '/app/generations/$jobId'
      path: '/generations/$jobId'
      fullPath: '/app/generations/$jobId'
      preLoaderRoute: typeof AppGenerationsJobIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/jobs': {
      id: '/app/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/app/admin/jobs'
      preLoaderRoute: typeof AppAdminJobsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/costs': {
      id: '/app/admin/costs'
      path: '/admin/costs'
      fullPath: '/app/admin/costs'
      preLoaderRoute: typeof AppAdminCostsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/p/$petSlug/posts/$postSlug': {
      id: '/p/$petSlug/posts/$postSlug'
      path: '/p/$petSlug/posts/$postSlug'
      fullPath: '/p/$petSlug/posts/$postSlug'
      preLoaderRoute: typeof PPetSlugPostsPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminCostsRoute: typeof AppAdminCostsRoute
  AppAdminJobsRoute: typeof AppAdminJobsRoute
  AppGenerationsJobIdRoute: typeof AppGenerationsJobIdRoute
  AppPetsPetIdRoute: typeof AppPetsPetIdRoute
  AppPetsNewRoute: typeof AppPetsNewRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppPetsIndexRoute: typeof AppPetsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminCostsRoute: AppAdminCostsRoute,
  AppAdminJobsRoute: AppAdminJobsRoute,
  AppGenerationsJobIdRoute: AppGenerationsJobIdRoute,
  AppPetsPetIdRoute: AppPetsPetIdRoute,
  AppPetsNewRoute: AppPetsNewRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppPetsIndexRoute: AppPetsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PPetSlugAboutRoute: PPetSlugAboutRoute,
  PPetSlugArchiveRoute: PPetSlugArchiveRoute,
  PPetSlugIndexRoute: PPetSlugIndexRoute,
  PPetSlugPostsPostSlugRoute: PPetSlugPostsPostSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
